### ISSUE TITLE
macOS Catalina Error: cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by raarellano** [ShogunPanda/alfred-chrome#4]
After upgrading to macOS Catalina I ran into several issues with this workflow. 

The first issue was 
> the external script may not have execute permission

To fix this issue I removed the workflow and added it again.

The second issue I received was:
> “alfred-chrome” cannot be opened because the developer cannot be verified.

To fix this issue: 
- I went into Alfred Workflows 
- Right clicked on the workflow
- Clicked on "open in finder"
- Opened terminal and moved into this directory (you can do this by adding `cd` and then dragging the directory into the terminal)
- I ran `chmod +x alfred-chrome`

This may be a specific issue on my system but decided to open an issue to help others that may be experiencing the same issue or hopefully, this can be fixed by updating the code.

**Comment by heyfletch** [comment]
Thanks for posting your steps. I also have the “alfred-chrome” cannot be opened issue, applied your steps, but my alfred-chrome was already set to executable. Same issue. Since Catalina is blocking it due to lack of signature, I'm wondering how just changing permissions worked in your case.

**Comment by heyfletch** [comment]
I solved it by following these steps: https://appuals.com/fix-cant-be-opened-because-it-is-from-an-unidentified-developer/

1) Press and hold the Control key and left–click on alfred-chrome
2) Open
3) Open

**Comment by ShogunPanda** [comment]
Sorry, I just saw this.
I've added instructions on the README.
