### ISSUE TITLE
Unable to run task!

### ISSUE THREAD

**Issue by nicolinden** [ShogunPanda/alfred-chrome#5]
On Mac OS Big Sur when calling the workflow I get the error "Unable to run task!". The full error is: 

Reason: Couldn't posix_spawn: error 85

The external script may not exist, or doesn't have execute (+x) permissions.

Related Workflow Info...
Name: 'Alfred Chrome'
Folder:/Users/nico/Dropbox/Applications/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2B739210-964E-4692-8471-955FFA57E07C

Any Idea if there is a solution for this or on which files I might try to give permissions so that it works again? I already gave execute permission to the "alfred-chrome" file in this directory but that does not solve it. I haven't found any issues with other  Alfred workflows on Big Sur. 

<img width="269" alt="Screenshot 2020-11-25 at 09 04 07" src="https://user-images.githubusercontent.com/13468895/100199240-34a89880-2efd-11eb-863f-53ddb9c4a2b6.png">

**Comment by paradox2222** [comment]
I second this! It's one of my most used Alfred items as I bounce between personal and educator chrome profiles. Any help in this matter is greatly appreciated.

**Comment by nickokgo** [comment]
Thrid it!

**Comment by cocobriclot** [comment]
Same problem here..

**Comment by aaronmeder** [comment]
Seems to be a general bug, at least since Big Sur. Would love to get it back :)

**Comment by fredlemieux** [comment]
Bummer :-(. Was looking forward to using this.


> Seems to be a general bug, at least since Big Sur. Would love to get it back :)

**Comment by kmthorsnes** [comment]
Anyone who have other working solutions?

**Comment by carsonjones** [comment]
Super sad about this. Anyone found an alternative or have an idea of how to fix?

**Comment by jsbrain** [comment]
@nicolinden did you try and check if the file is actually there and if so, has the correct permissions?

**Comment by oguzgelal** [comment]
I solved this by adding `#!/bin/bash` to the beginning of the file

**Comment by joseinazusa** [comment]
The issue appears to be caused by the executable being compiled with older libraries.  I compiled and repackaged the workflow.  The spawn issue appears to be fixed.  I forked the project so I could do a pull request.  You can recompile alfredchrome.go.  If you want to just get the workflow, you can go to the forked project.  No code was changed, only recompiled with updated libraries.

**Comment by nicolinden** [comment]
> The issue appears to be caused by the executable being compiled with older libraries. I compiled and repackaged the workflow. The spawn issue appears to be fixed. I forked the project so I could do a pull request. You can recompile alfredchrome.go. If you want to just get the workflow, you can go to the forked project. No code was changed, only recompiled with updated libraries.

Wow this seems to work indeed, I'll will keep trying it the coming days but I believe you are a life saver :-)

**Comment by kmthorsnes** [comment]
> The issue appears to be caused by the executable being compiled with older libraries. I compiled and repackaged the workflow. The spawn issue appears to be fixed. I forked the project so I could do a pull request. You can recompile alfredchrome.go. If you want to just get the workflow, you can go to the forked project. No code was changed, only recompiled with updated libraries.

Thank you so much for this! This save my day! (and probably a lot of days ahead) :)

**Comment by nicolinden** [comment]
Problem is solved by the suggestion of @joseinazusa thanks all for looking into this, I am glad that this workflow works again!
